# Generated by Django 5.1.6 on 2025-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, choices=[('1', 'Pastor'), ('2', 'Presbitero'), ('3', 'Diacono'), ('4', 'Obreiro'), ('5', 'Musico'), ('6', 'Vocal')], max_length=25, null=True),
        ),
    ]
