# Generated by Django 5.1.6 on 2025-03-11 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='participantes',
        ),
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.CharField(blank=True, choices=[('1', 'Cantor'), ('2', 'Guitarrista'), ('3', 'Baterista')], max_length=10, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='escala',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(through='core.Escala', to=settings.AUTH_USER_MODEL),
        ),
    ]
